# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
    - linux
    - osx
    - windows
julia:
    - 1.3
    - 1.4
    - 1.5
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
# script:
#     - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#     - julia --project -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("PATHSolver");  Pkg.build("PATHSolver"); Pkg.test("PATHSolver", coverage=true)'

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

# after_success:
#     - echo $TRAVIS_JULIA_VERSION
#     - julia -e 'using Pkg; cd(Pkg.dir("PATHSolver")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
